apiVersion: v1
kind: Service
metadata:
  name: service-primary
  namespace: default
spec:
  selector:
    app: primary
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: custom-port
      protocol: TCP
      port: 30899
      targetPort: 80
  type: LoadBalancer
